---
title: "MPD results for ssm3"
author: "Anthony Davidson"
date: "07/04/2020"
output: 
  bookdown::html_document2: 
   theme: united
   highlight: tango
   fig_caption: yes
   toc: yes
   toc_float: true
   code_folding: hide
   df_print: paged
   number_sections: false
   output_dir: "docs"
editor_options: 
  chunk_output_type: console
---
  
## Import data {.tabset}

```{r april2020-setup, include=FALSE}
# suppressWarnings(suppressMessages(suppressPackageStartupMessages({
# source("C:/Rscripts/source.R")
# })
knitr::opts_chunk$set(echo = F, warning = F, message = F)
library(kableExtra)


# sets paths for computers with other software components
# this code block produces an enviroment warning
# but not sure how to sort depenancies still
# Feb2020
# myPaths <- .libPaths("C:/Program Files/R/R-3.6.2/library")
# myPaths <- c(myPaths)
# .libPaths(myPaths)  # add new path
# .libPaths()
```

### Orginal data

```{r}
require(tidyverse)
require(jagsUI)
  
  # setwd("c:\\users\\s429217\\onedrive\\data\\mpd\\state space\\data")
  
############################################################################
## Read in rat, mouse and possum abundance data on log scale

  rat.pos <- read.csv(here::here("data/raw/Rat possum mouse log N estimates.csv"))
  rat.pos <- dplyr:::select(rat.pos, -X)
  # glimpse(rat.pos)          
  
  #ant added
  # choose species
  rat.pos$xx <- rat.pos$rat_abun
  rat.pos$xxse <- rat.pos$rat_sd
  
  # choose treatments
  # exclude "Possum + rat removal" treatment when analysing rats
  # exclude the possum removal treatments when analysing possums
  
  rat.pos <- filter(rat.pos, treat %in% c("Possum removal", "Control", "Stoat removal"))
  
  # exclude first two trips
  rat.pos <- filter(rat.pos, month > 2)     
  
# exclude first few trips
  # table(rat.pos$month)
  # rat.pos <- filter(rat.pos, month > 2)
  
  
  # ggplot(rat.pos, aes(y = xx, x = month)) +
  #   geom_point() +
  #   geom_line(data = filter(rat.pos, !is.na(xx))) +
  #   geom_errorbar(aes(ymin = xx - xxse, ymax = xx + xxse)) +
  #   facet_wrap(~ grid) +
  #   theme_bw()                                                          
  
############################################################################
## Read in seed trap data
  trap <- read.csv(here::here("data/raw/seed trap data.csv"))
  trap <- dplyr:::select(trap, -X)
  # glimpse(trap)
  
  trap$month <- ifelse(trap$grid == "Okopeka East" & is.na(trap$month) == T, 31, trap$month)
  trap$month <- ifelse(trap$grid == "Okopeka West" & is.na(trap$month) == T, 31, trap$month)
  
## Summarise by seed trap, summing seed dry weights
  seed.trap <- group_by(trap, seed.trap, grid, month) %>%
               summarise(seed_mass = sum(dry.wt, na.rm=T),
               seed_mass_poss_pref = sum(dry.wt[spp %in% c("Beitaw", "Eladen", "Rubcis", "Melram", "Hedarb", "Pencor")], na.rm=T),
               seed_mass_poss_avoid = sum(dry.wt[spp %in% c("Ripsca", "Prufer")], na.rm=T))

# convert to log scale
  seed.trap <- seed.trap %>%
               mutate(seed_mass = log(seed_mass + 0.001),
                      seed_mass_poss_pref = log(seed_mass_poss_pref + 0.001),
                      seed_mass_poss_avoid = log(seed_mass_poss_avoid + 0.001))
                     
# now summarise by grid and month calculating mean seed trap values
  mean.seed <- group_by(seed.trap, grid, month) %>%
               summarise(seed_mass = mean(seed_mass, na.rm=T),
               seed_mass_poss_pref = mean(seed_mass_poss_pref, na.rm=T),
               seed_mass_poss_avoid = mean(seed_mass_poss_avoid, na.rm=T)) 
               
  # ggplot(mean.seed, aes(y = seed_mass, x = month)) +
  #   geom_point() +
  #   geom_line(data = filter(mean.seed, !is.na(seed_mass))) +
  #   facet_wrap(~ grid) +
  #   theme_bw()
                  
  
############################################################################
  
  dat <- left_join(rat.pos, mean.seed)
  dat <- mutate(dat, grid = factor(grid))
  
## Define years
  dat$year <- 4            
  dat$year <- ifelse(dat$month <= 30, 3, dat$year)
  dat$year <- ifelse(dat$month <= 18, 2, dat$year)
  dat$year <- ifelse(dat$month <= 6, 1, dat$year)
  # table(dat$month, dat$year)
  
# convert to decimal years
  dat$year.dec <- dat$month / 12
  

############################################################################
# model abundance
################################################################################
# matrices to store data

# N is mean estimated log abundance from mark-recapture model 
  N.rat <- tapply(dat$rat_abun, list(dat$year.dec, dat$grid), mean)

# Nse is standard error of log abundance from mark-recapture model
  Nse.rat <- tapply(dat$rat_sd, list(dat$year.dec, dat$grid), mean)
# convert Nse to precision
  Ntau.rat <- 1 / Nse.rat^2

  N.poss <- tapply(dat$poss_abun, list(dat$year.dec, dat$grid), mean)
  Nse.poss <- tapply(dat$poss_sd, list(dat$year.dec, dat$grid), mean)
  Ntau.poss <- 1 / Nse.poss^2

  N.mouse <- tapply(dat$mouse_abun, list(dat$year.dec, dat$grid), mean)
  Nse.mouse <- tapply(dat$mouse_sd, list(dat$year.dec, dat$grid), mean)
  Ntau.mouse <- 1 / Nse.mouse^2

################################################################################
  seed <- tapply(dat$seed_mass, list(dat$year.dec, dat$grid), mean)
# centre seed
  nseed <- (seed - mean(seed, na.rm = T))

# measurement time
  year.dec <- as.numeric(rownames(seed))

# time gap between measurements
  td <- year.dec - lag(year.dec)
  
  nYears <- dim(N.rat)[1]
  nGrids <- dim(N.rat)[2]
  
# coding to identify Possum + rat removal grids
  prr <- ifelse(table(dat$treat, dat$grid)[2, ] > 0, 1, 0)
```

### Jags output

```{r}
require(DT)
mod.jags <- readRDS("./data/mod_jags_april3-TO-1v3.rds")
mod.sum <- mod.jags$summary
DT::datatable(mod.sum[1:30, c(1, 3, 7, 8, 9)])
```

### Previous plots richard

```{r}
################################################################################
# results of modelling missing seed values at each site
  estr <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 4) == "seed", c(1, 4, 6, 8)])
  names(estr) <- c("mp", "lcl", "ucl", "rhat")
  estr$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  estr$grid <- rep(levels(factor(dat$grid)), each = nYears)
  
# if rhat is non-missing then seed was estimated
  estr$est <- ifelse(is.na(estr$rhat), 0, 1)
  
  ggplot(estr, aes(y = mp, x = month)) +
    geom_line() +
    geom_point(aes(colour = factor(est))) +
    geom_errorbar(aes(ymin = lcl, ymax = ucl, colour = factor(est)), width = 0, alpha = 0.5) +
    facet_wrap(~ grid) +
    theme_classic() +
    theme(legend.position = "top")

################################################################################
# extract the model fitted to each grid and plot
  x <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 5) == "X.rat", c(1, 3, 7)])
  names(x) <- c("X.rat", "lcl.X.rat", "ucl.X.rat")
  x$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  x$grid <- rep(levels(factor(dat$grid)), each = nYears)

  simx <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 8) == "simX.rat", c(1, 3, 7)])
  names(simx) <- c("simX.rat", "lcl.simX.rat", "ucl.simX.rat")
  simx$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  simx$grid <- rep(levels(factor(dat$grid)), each = nYears)
  
# merge with the actual site data
  nsite <- left_join(dat, simx)
  nsite <- left_join(nsite, x)


# fitted process model is the red line
# circles are the grid data
# black line is the estimate of the true population having accounted for observation error (e.g. variation between grids at the same site)

  ggplot(nsite, aes(y = exp(rat_abun), x = month)) +
    geom_point(size = 3) +
    geom_line(aes(y = exp(X.rat)), lwd = 1) +
    geom_line(aes(y = exp(simX.rat)), colour = "red", lwd = 1) +
    facet_wrap(~ grid) +
    theme_classic() +
    theme(legend.position = "none")

################################################################################
# extract the model fitted to each grid and plot
  x <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 6) == "X.poss", c(1, 3, 7)])
  names(x) <- c("X.poss", "lcl.X.poss", "ucl.X.poss")
  x$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  x$grid <- rep(levels(factor(dat$grid)), each = nYears)

  simx <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 9) == "simX.poss", c(1, 3, 7)])
  names(simx) <- c("simX.poss", "lcl.simX.poss", "ucl.simX.poss")
  simx$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  simx$grid <- rep(levels(factor(dat$grid)), each = nYears)
  
# merge with the actual site data
  nsite <- left_join(dat, simx)
  nsite <- left_join(nsite, x)


# fitted process model is the red line
# circles are the grid data
# black line is the estimate of the true population having accounted for observation error (e.g. variation between grids at the same site)

  ggplot(nsite, aes(y = exp(poss_abun), x = month)) +
    geom_point(size = 3) +
    geom_line(aes(y = exp(X.poss)), lwd = 1) +
    geom_line(aes(y = exp(simX.poss)), colour = "red", lwd = 1) +
    facet_wrap(~ grid) +
    theme_classic() +
    theme(legend.position = "none")
    
################################################################################
# extract the model fitted to each grid and plot
  x <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 7) == "X.mouse", c(1, 3, 7)])
  names(x) <- c("X.mouse", "lcl.X.mouse", "ucl.X.mouse")
  x$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  x$grid <- rep(levels(factor(dat$grid)), each = nYears)

  simx <- data.frame(mod.sum[substr(rownames(mod.sum), 1, 10) == "simX.mouse", c(1, 3, 7)])
  names(simx) <- c("simX.mouse", "lcl.simX.mouse", "ucl.simX.mouse")
  simx$month <- rep(as.numeric(levels(factor(dat$month))), nGrids)
  simx$grid <- rep(levels(factor(dat$grid)), each = nYears)
  
# merge with the actual site data
  nsite <- left_join(dat, simx)
  nsite <- left_join(nsite, x)


# fitted process model is the red line
# circles are the grid data
# black line is the estimate of the true population having accounted for observation error (e.g. variation between grids at the same site)

  ggplot(nsite, aes(y = exp(mouse_abun), x = month)) +
    geom_point(size = 3) +
    geom_line(aes(y = exp(X.mouse)), lwd = 1) +
    geom_line(aes(y = exp(simX.mouse)), colour = "red", lwd = 1) +
    facet_wrap(~ grid) +
    theme_classic() +
    theme(legend.position = "none")
```

## My plot options {.tabset}

```{r}
#sorting out results my way...
require(DT)

mod.jags <- readRDS("./data/mod_jags_april3-TO-1v3.rds")
mod.sum <- mod.jags$summary
```

### Overall trends

```{r}
# str(nsite)
source(here::here("R/davidson_2020_theme.r"))
nsite.ant <- nsite %>%
              transmute(grid = grid,
                        trip = month)

ggplot(nsite, aes(y = exp(mouse_abun), x = month)) +

    geom_line(aes(y = exp(X.mouse)), colour = "black", lwd = 0.7, lty = 2, alpha = 0.7) +
    geom_line(aes(y = exp(simX.mouse)), colour = "red", lwd = 0.7, lty = 2, alpha = 0.7) +
    geom_point(data = nsite, aes(y = exp(mouse_abun), x = month), lwd = 2,size = 4, shape = 21, col = "black", fill = "white") +
    facet_wrap(~ grid) +
    
    # theme_classic() +
    theme_davidson_2020()
```

### Model convergance

```{r}
require(tidybayes)
# vignette("tidybayes")

require(MCMCvis)
# vignette("MCMCintro")

#load example data
data(MCMC_data)

#run summary function
MCMCsummary(MCMC_data, 
             params = 'beta')


out_tib_summary <- as_tibble(mod.jags$summary)

# glimpse(out_tib_summary)
#not needed
# gsub(names(out_tib_summary), "`", "")
# tidybayes::gather_variables(out_tib_summary)
# tidybayes::gather_variables(out_tib_summary)
```

### MCMCvis

```{r}
chains <- MCMCvis::MCMCchains(mod.jags)
str(chains)
plot(chains)
# MCMCvis::MCMCsummary(mod.jags)

# MCMCtrace(mod.jags)
# tidybayes::combine_chains()

# MCMCvis::MCMCplot(mod.jags)
# MCMCvis::MCMCpstr(mod.jags)

mod.jags.chains <- MCMCvis::MCMCchains(mod.jags)
# MCMCvis::MCMCplot(mod.jags.chains)

```

